openapi: 3.1.0
info:
  title: Buscar Template no Supabase
  description: Busca o primeiro template ativo e retorna o campo 'json'
  version: '1.0.0'
servers:
  - url: https://bbypogwrzjvdlcttiiqb.supabase.co
paths:
  /rest/v1/templates:
    get:
      summary: Buscar template ativo
      operationId: buscarTemplate
      parameters:
        - name: ativo
          in: query
          required: true
          schema:
            type: string
            example: eq.true
        - name: select
          in: query
          required: true
          schema:
            type: string
            example: json
        - name: limit
          in: query
          required: true
          schema:
            type: string
            example: 1
      responses:
        '200':
          description: Retorna o JSON do primeiro template ativo
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    json:
                      type: object
      x-openai-isConsequential: false
      x-openai-headers:
        apikey: >-
          eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJieXBvZ3dyemp2ZGxjdHRpaXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njc2NzQsImV4cCI6MjA2MjA0MzY3NH0.SCaI-jMvBaWUj4T7PKATEisuVXhUxBK9oYLxVrS8ufE
        Authorization: >-
          Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJieXBvZ3dyemp2ZGxjdHRpaXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0Njc2NzQsImV4cCI6MjA2MjA0MzY3NH0.SCaI-jMvBaWUj4T7PKATEisuVXhUxBK9oYLxVrS8ufE
components:
  schemas: {}
