openapi: 3.1.0
info:
  title: Buscar Template no Supabase
  description: Busca o primeiro template ativo na tabela 'templates' e retorna o campo 'json'.
  version: 1.0.0
servers:
  - url: https://bbypogwrzjvdlcttiiqb.supabase.co
paths:
  /rest/v1/templates:
    get:
      summary: Buscar template ativo
      operationId: buscarTemplate
      parameters:
        - name: ativo
          in: query
          required: true
          schema:
            type: string
            enum: ["eq.true", "eq.false"]  # Restringe os valores válidos
            example: eq.true
        - name: select
          in: query
          required: true
          schema:
            type: string
            example: json
        - name: limit
          in: query
          required: true
          schema:
            type: string
            example: 1
      responses:
        "200":
          description: Retorna o JSON do primeiro template ativo
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    json:
                      type: object
      security:
        - api_key: []
components:
  securitySchemes:
    api_key:
      type: apiKey
      in: header
      name: apikey
  schemas: {}
